# Generated by Django 3.2.13 on 2022-06-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='company',
            field=models.CharField(max_length=255, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='industry',
            field=models.CharField(max_length=255, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='job_title'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=255, verbose_name='message'),
        ),
    ]
