# Generated by Django 3.2.13 on 2022-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220630_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1', models.CharField(max_length=255, verbose_name='company')),
                ('industry1', models.CharField(max_length=255, verbose_name='industry')),
                ('firstname1', models.CharField(max_length=255, verbose_name='firstname')),
                ('lastname1', models.CharField(max_length=255, verbose_name='lastname')),
                ('job_title1', models.CharField(max_length=255, verbose_name='job_title')),
                ('email1', models.CharField(max_length=255, verbose_name='email')),
                ('message1', models.CharField(max_length=255, verbose_name='message')),
            ],
        ),
    ]
